openapi: 3.1.0
info:
  title: WebOps Mini
  version: "1.0.0"
servers:
  - url: https://gloom-runtime.onrender.com
paths:
  /open:
    post:
      operationId: open
      summary: Open a URL and wait
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [url]
              properties:
                url:
                  type: string
                wait:
                  type: string
                  enum: [load, domcontentloaded, networkidle0]
                  default: networkidle0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url: { type: string }
                  title: { type: string }
  /text:
    post:
      operationId: getText
      summary: Get innerText of a selector
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [selector]
              properties:
                selector: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  text: { type: string }
  /click:
    post:
      operationId: click
      summary: Click a selector
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [selector]
              properties:
                selector: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
  /type:
    post:
      operationId: type
      summary: Type into a selector
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [selector, text]
              properties:
                selector: { type: string }
                text: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
  /shot:
    post:
      operationId: screenshot
      summary: Screenshot full page
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  path: { type: string }
